version: "3.9"


services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - nginx-proxy
  acme-companion:
    image: nginxproxy/acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=emingaliev@i-neti.ru
      - LETSENCRYPT_EMAIL=emingaliev@i-neti.ru
      - NGINX_PROXY_CONTAINER=nginx_proxy_nginx-proxy_1
    depends_on:
      - nginx-proxy

networks:
    nginx-proxy:
      name: nginx-proxy

volumes:
  certs:
  vhost:
  html:
  acme: